export enum AUTH_CALLBACK_ERROR_CODE {
  AUTH_TOKEN_EXCHANGED_FAILED = "AUTH_TOKEN_EXCHANGED_FAILED",
  AUTH_UNKNOWN_ERROR = "AUTH_UNKNOWN_ERROR",
}

export enum API_ERROR_CODE {
  AUTH_EXPIRED = "AUTH_EXPIRED",
  AUTH_REQUIRED = "AUTH_REQUIRED",
  USER_NOT_EXISTED = "USER_NOT_EXISTED",
  APPOINTMENT_NOT_EXISTED = "APPOINTMENT_NOT_EXISTED",
  HOST_NOT_ALLOWED = "HOST_NOT_ALLOWED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  NOT_JOINED_APPOINTMENT = "NOT_JOINED_APPOINTMENT",
  ALREADY_EXISTS = "ALREADY_EXISTS",
}
