export enum AUTH_CALLBACK_ERROR_CODE {
  AUTH_TOKEN_EXCHANGED_FAILED = "AUTH_TOKEN_EXCHANGED_FAILED",
  AUTH_UNKNOWN_ERROR = "AUTH_UNKNOWN_ERROR",
}

export enum API_ERROR_CODE {
  AUTH_EXPIRED = "AUTH_EXPIRED",
  AUTH_REQUIRED = "AUTH_REQUIRED",
}
